{% set name = "XlsxWriter" %}
{% set version = "1.2.4" %}
{% set sha256 = "025115efe76e5487301e5bb11cabc9167179e483ea20d85aab9de9bc4cc2b752" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - xlsxwriter

about:
  home: https://xlsxwriter.readthedocs.io/
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Python module for creating Excel XLSX files'
  description: |
    XlsxWriter is a Python module that can be used to write text, numbers, formulas
    and hyperlinks to multiple worksheets in an Excel 2007+ XLSX file.
  dev_url: https://github.com/jmcnamara/XlsxWriter
  doc_url: https://xlsxwriter.readthedocs.org/
  doc_source_url: https://github.com/jmcnamara/XlsxWriter/blob/master/docs/XlsxWriter.pdf

extra:
  recipe-maintainers:
    - mcs07
    - nehaljwani
