{% set name = "XlsxWriter" %}
{% set version = "3.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jmcnamara/{{ name }}/archive/refs/tags/RELEASE_{{ version }}.tar.gz
  sha256: bab634b7cb46ad0dd184c47ca818b882aa83c1e472609f1dbe2701e99f68a081

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  source_files:
    - xlsxwriter/test
    - xlsxwriter/
  imports:
    - xlsxwriter
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv xlsxwriter/test

about:
  home: https://xlsxwriter.readthedocs.io/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A Python module for creating Excel XLSX files
  description: |
    XlsxWriter is a Python module that can be used to write text, numbers, formulas
    and hyperlinks to multiple worksheets in an Excel 2007+ XLSX file.
  dev_url: https://github.com/jmcnamara/XlsxWriter
  doc_url: https://xlsxwriter.readthedocs.io

extra:
  recipe-maintainers:
    - mcs07
    - nehaljwani
