{% set name = "XlsxWriter" %}
{% set version = "1.1.7" %}
{% set sha256 = "2a40b427dac0f640031e5b33abe97e761de6e0f12d4d346e7b2e2b67cf6ee927" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - xlsxwriter

about:
  home: https://xlsxwriter.readthedocs.io/
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'A Python module for creating Excel XLSX files'
  description: |
    XlsxWriter is a Python module that can be used to write text, numbers, formulas
    and hyperlinks to multiple worksheets in an Excel 2007+ XLSX file.
  dev_url: https://github.com/jmcnamara/XlsxWriter
  doc_url: https://xlsxwriter.readthedocs.org/
  doc_source_url: https://github.com/jmcnamara/XlsxWriter/blob/master/docs/XlsxWriter.pdf

extra:
  recipe-maintainers:
    - mcs07
    - nehaljwani
