travis:
  secure:
    BINSTAR_TOKEN: ZrdwW5rfxda6VStWJ8PREikvRmjIM1xj5HyhmZw4QpOIVATn7gTrzx6YzhabxHbI9Fsww6DLL/vgkazpoWFMyu6sYULp2C0itNKfu4d1em4RKYkjVtOdtS+bJu7yNQvHDyjTGumc9hYvn7AyRM+eO8CjGIdWSXz5GBO1v9VwthJYvavbn1cdMuhtRuSFk9pJ6p30kcBeH2O2xEDHbVuB9M4eJOIjZiUzlNneHsZj5JP8kXm4TZEGJKm9fXOsxm2pZn5XpbAj8+kIpVAo7plpw1VZ+G0CO8C4VJSdmKdpQpa2V+HKTsyExNoudwXbIpcWpfW1+gqwchjJcTb9t1HlWT0MGKE65ZW1gO+M0QBaCjD2l33GBIqoBmxyx+fBn9dn6uDxxHa+eioh2ElkGJMuxuwVP6EpA6MuCAxsI6nX0p91xQT8hnLHPDTeCd0gtQcoDGOLFOg1HonpZYqkZTsDfDzusI9wqN84JMqi96v21ihCVWC1GEnPr5e3sBcNd8DV/LT+KSuDtFyFC14XXKs7wcooxftD3r2irjgoXRTPIrJ7xIw4N+wLBuLnz7VAOsqiQ6Vk3lGEYlJ9sOlT7CEInSvwxFzkDqzA20RpsSMBaZYmLffK8Ru17SGe49CaXGMi5vouzhfGwFvQ+gycrAsGOE9JKPn6XuFFrFZLmEvmg1E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
