travis:
  secure:
    BINSTAR_TOKEN: N+c1mUID0rFEOazEq+RhssokVTREjapkToQswuxuSKdNm7g5xosWKnYrhwVZtYhy8xYd0F3aJYDnf3fcggYqMSni6boUYmGBsuVAguDk/DesKILgxy/Xc1cvLp6f+18eAOqMZxNWypKyKLjBxoJKImGOjkHMJmjWlrLkK04j5HwGvTnDgMKeAvOkptc7VxswgFBsAn34CST6WbWJey8evG5xEO3ek5uDG04n3vdj5MVTVas1JSPiZkzaqd7rvfh27TmBqbbI6xVDVoW39wICbBy6pGtKs89vH7icXJAcZQszKmbLWEa8WRA40yfpLd4wLHobTl+5rccJaV2lFIzQfSOPFM4Su+M/tuQMobOkssZTjVETjbSJ5YP5kI0afFxXyJisoZWR72jHldkJZkgocCJqF1cImoyd38RpPFGPo/h+ervVinrAer+LVvXWKKSSnzV35sOpCml9mfjhc6avwXF7JeFlTkusLZq7RJWy5DJ7yOaDbPRvN/HE8k2zZmzuEbgYLjvIN+QcllHRM6aNvbaaPQNkpcBxbKwRezd+ND+iTHCGspl1hlKg+Zvq0/B4K58FqspTDE+Yp+Cf+qDhzLsJPTjwQ9sF5Aus/Jj5cPTPvsEYYHG0emN7bGXWv4MB/WlNRWzY0xDt4LPAlcxPTX0WuWw1GIWISAICjVWPNOk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
