travis:
  secure:
    BINSTAR_TOKEN: IYl5Kxs7XIBHtc29akwe6IKSCc9u3FgogsLQKdE84a5ety2afRh7wssOWiW4h7GH45WGvNthGblC8yOtMoM5RME0OEMcblYp2Wccl60A2WBZyZQYdcvJkZt9m5lpt0aBKxQpyVRhie+F8I44wqlNHBvHscZC0SztwjXGS+GddH8kOaoJ5IpECIRlAz1WBg6eRcxJQRf6G6aA5bof6y7mNR7gIbkPd/jkYaLb3SgC7JMORVgpFelANqayh5jG2vi+i700O1QChf1lP+ZBFOPy5EaA0XXokCfuflxEIg15wnvXLe64KeO1y1McdCvnK1vBRQMhKeiPFFpE3I4xUmS6jvVPXfV1Imr28G9CChfrd6+KS/U5DETbMDRg2+E4y+5BflwOMJTiATplfFCWI/rnKWSTYHcHc063PgzkuI//EAgwRrGI61CiOjZ4iGRweqLSnjjFL/zqgUtOAqzU3pw9U4i7ySLF9PBuBD99S7haJxYilk1wLc954VwY1//KRAaCCfzNVtIubGoSX/uadfbvfn7KId5oog2402V3Cd4ZHq+4TK3RCcyn3W3Z836sLdXqChyvKxEOv0EuMte4F4Wrj5xWb3SFjtrKfuU5SwU2c6+5UZcTvjgUvzRWdk9Bh/s1Omb82lBb6RcNlzMaf9IijYvW14trWn0bExLXkvxgO9M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
